In [1]:
import torch
from torch import nn
import math
import torch.nn.functional as F

In [2]:
torch.manual_seed(0)

In [3]:
y_in = torch.rand(3,4)

In [4]:
y_tgt = torch.randint(0,4,(3,), dtype=torch.int64)

In [5]:
y_in, y_tgt

(tensor([[0.4963, 0.7682, 0.0885, 0.1320],
         [0.3074, 0.6341, 0.4901, 0.8964],
         [0.4556, 0.6323, 0.3489, 0.4017]]),
 tensor([0, 3, 2]))

loss = F.cross_entropy(y_in, y_tgt) = F.nll_loss(F.log_softmax(y_in), y_tgt)

In [7]:
F.cross_entropy(y_in, y_tgt) , F.cross_entropy(y_in, y_tgt) - F.nll_loss(F.log_softmax(y_in, dim=1), y_tgt)

(tensor(1.2997), tensor(0.))

In [8]:
F.log_softmax(y_in, dim=1)

tensor([[-1.3008, -1.0289, -1.7086, -1.6651],
        [-1.6844, -1.3577, -1.5017, -1.0953],
        [-1.3961, -1.2194, -1.5029, -1.4500]])

In [9]:
lsm = (y_in.exp().t()/y_in.exp().sum(dim=1)).t().log()

In [10]:
lsm

tensor([[-1.3008, -1.0289, -1.7086, -1.6651],
        [-1.6844, -1.3577, -1.5017, -1.0953],
        [-1.3961, -1.2194, -1.5029, -1.4500]])

In [11]:
lsm.gather(1, y_tgt.view(-1,1)).mean()

tensor(-1.2997)