In [1]:
import torch
from torch import nn

In [8]:
x = torch.randint(1,11,(2,3,4))

In [11]:
x, x.shape

(tensor([[[ 6,  8,  8,  1],
          [ 5,  2,  3,  2],
          [ 2,  2,  6,  6]],
 
         [[ 2,  9,  4,  7],
          [ 2,  5, 10,  4],
          [ 9,  7, 10,  8]]]),
 torch.Size([2, 3, 4]))

In [12]:
x.reshape(-1)

tensor([ 6,  8,  8,  1,  5,  2,  3,  2,  2,  2,  6,  6,  2,  9,  4,  7,  2,  5,
        10,  4,  9,  7, 10,  8])

In [16]:
x.reshape(2, -1), x.reshape(2, -1).shape

(tensor([[ 6,  8,  8,  1,  5,  2,  3,  2,  2,  2,  6,  6],
         [ 2,  9,  4,  7,  2,  5, 10,  4,  9,  7, 10,  8]]),
 torch.Size([2, 12]))

In [15]:
x.reshape(3, 2, -1), x.reshape(3, 2, -1).shape

(tensor([[[ 6,  8,  8,  1],
          [ 5,  2,  3,  2]],
 
         [[ 2,  2,  6,  6],
          [ 2,  9,  4,  7]],
 
         [[ 2,  5, 10,  4],
          [ 9,  7, 10,  8]]]),
 torch.Size([3, 2, 4]))

In [17]:
x.shape

torch.Size([2, 3, 4])

In [20]:
x.permute(0,2,1), x.permute(0,2,1).shape

(tensor([[[ 6,  5,  2],
          [ 8,  2,  2],
          [ 8,  3,  6],
          [ 1,  2,  6]],
 
         [[ 2,  2,  9],
          [ 9,  5,  7],
          [ 4, 10, 10],
          [ 7,  4,  8]]]),
 torch.Size([2, 4, 3]))

In [21]:
x.permute(0,2,1) - x.transpose(1,2)

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])