In [1]:
import torch
from torch import nn

In [5]:
a = torch.tril(torch.ones(5,5))

In [9]:
a, a.shape

(tensor([[1., 0., 0., 0., 0.],
         [1., 1., 0., 0., 0.],
         [1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 0.],
         [1., 1., 1., 1., 1.]]),
 torch.Size([5, 5]))

In [10]:
a.unsqueeze(0), a.unsqueeze(0).shape

(tensor([[[1., 0., 0., 0., 0.],
          [1., 1., 0., 0., 0.],
          [1., 1., 1., 0., 0.],
          [1., 1., 1., 1., 0.],
          [1., 1., 1., 1., 1.]]]),
 torch.Size([1, 5, 5]))

In [11]:
a.unsqueeze(0).unsqueeze(0), a.unsqueeze(0).unsqueeze(0).shape

(tensor([[[[1., 0., 0., 0., 0.],
           [1., 1., 0., 0., 0.],
           [1., 1., 1., 0., 0.],
           [1., 1., 1., 1., 0.],
           [1., 1., 1., 1., 1.]]]]),
 torch.Size([1, 1, 5, 5]))

In [16]:
a.unsqueeze(-1), a.unsqueeze(-1).shape

(tensor([[[1.],
          [0.],
          [0.],
          [0.],
          [0.]],
 
         [[1.],
          [1.],
          [0.],
          [0.],
          [0.]],
 
         [[1.],
          [1.],
          [1.],
          [0.],
          [0.]],
 
         [[1.],
          [1.],
          [1.],
          [1.],
          [0.]],
 
         [[1.],
          [1.],
          [1.],
          [1.],
          [1.]]]),
 torch.Size([5, 5, 1]))

In [30]:
mask = torch.tril((torch.ones(5,5)==1))

In [33]:
mask = (mask==False)

In [34]:
mask

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [22]:
b = torch.rand((5,5))

In [23]:
b

tensor([[0.6625, 0.1496, 0.8916, 0.3994, 0.6412],
        [0.7657, 0.5091, 0.7086, 0.3593, 0.3866],
        [0.0441, 0.2587, 0.8087, 0.5764, 0.3573],
        [0.7139, 0.0256, 0.3020, 0.8442, 0.4189],
        [0.1742, 0.7784, 0.6568, 0.6233, 0.1597]])

In [36]:
b.masked_fill(mask, -torch.inf)

tensor([[0.6625,   -inf,   -inf,   -inf,   -inf],
        [0.7657, 0.5091,   -inf,   -inf,   -inf],
        [0.0441, 0.2587, 0.8087,   -inf,   -inf],
        [0.7139, 0.0256, 0.3020, 0.8442,   -inf],
        [0.1742, 0.7784, 0.6568, 0.6233, 0.1597]])