In [8]:
import torch
from torch import nn
import math
import torch.nn.functional as F

In [18]:
batch_size = 3
d_model = 8
seq_length = 5
vocab_length = 20

In [19]:
x = torch.randint(0, vocab_length, (batch_size, seq_length))

In [20]:
emb = nn.Embedding(vocab_length, d_model)

In [21]:
x.shape

torch.Size([3, 5])

In [22]:
emb(x).shape

torch.Size([3, 5, 8])

In [23]:
x

tensor([[17, 11, 13, 10, 14],
        [ 8, 16,  9,  5,  7],
        [ 3, 13,  3, 17, 17]])

In [24]:
pos_emb = nn.Embedding(seq_length, d_model)

In [26]:
pos_emb.weight

Parameter containing:
tensor([[ 0.6887,  0.5245,  0.4675,  1.4110,  0.5283, -0.4089, -0.5095, -1.1440],
        [ 0.2648, -1.2524, -1.4919, -0.0045, -0.1085,  1.3737,  0.2537,  0.0600],
        [-1.4652, -0.0575, -0.8603,  0.5402,  0.0211, -0.6835,  0.5369,  0.5124],
        [-0.2174, -0.2244,  0.3186,  0.1249,  0.6546, -0.9558,  0.3548, -1.1349],
        [ 1.0614,  1.1902,  2.3601,  0.9422, -1.1918,  1.1141, -0.1132,  1.0314]],
       requires_grad=True)

In [27]:
pos_emb(torch.arange(3))

tensor([[ 0.6887,  0.5245,  0.4675,  1.4110,  0.5283, -0.4089, -0.5095, -1.1440],
        [ 0.2648, -1.2524, -1.4919, -0.0045, -0.1085,  1.3737,  0.2537,  0.0600],
        [-1.4652, -0.0575, -0.8603,  0.5402,  0.0211, -0.6835,  0.5369,  0.5124]],
       grad_fn=<EmbeddingBackward0>)