In [2]:
import torch
from torch import nn

In [3]:
w1 = nn.Linear(in_features=2,out_features=3,bias=False)

In [4]:
w2 = nn.Linear(in_features=3,out_features=4,bias=False)

In [5]:
model = nn.Sequential(w1, w2)

In [6]:
x = torch.rand(5,2)

In [7]:
y = model(x)

In [8]:
y.shape

torch.Size([5, 4])

In [9]:
x @ w1.weight.t() @ w2.weight.t() - y

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], grad_fn=<SubBackward0>)

In [23]:
class Test1(nn.Module):   
    def __init__(self):
        super().__init__()
        torch.manual_seed(3)
        
        m = nn.ModuleList([nn.Linear(in_features=3,out_features=3,bias=False) for _ in range(4)])
        self.model = nn.Sequential(*m)
        
    def forward(self, x):
        return self.model(x)

In [27]:
class Test2(nn.Module):   
    def __init__(self):
        super().__init__()
        torch.manual_seed(3)
        
        self.m = [nn.Linear(in_features=3,out_features=3,bias=False) for _ in range(4)]
        
    def forward(self, x):
        for i in range(4):
            x = self.m[i](x)
        return x

In [28]:
x = torch.rand(3,3)

In [29]:
m1 = Test1()

In [30]:
y1 = m1(x)

In [31]:
m2 = Test2()

In [32]:
y2 = m2(x)

In [33]:
y1

tensor([[ 0.0592, -0.0111,  0.0238],
        [ 0.1033, -0.0216,  0.0483],
        [ 0.1105, -0.0206,  0.0440]], grad_fn=<MmBackward0>)

In [34]:
y2

tensor([[ 0.0592, -0.0111,  0.0238],
        [ 0.1033, -0.0216,  0.0483],
        [ 0.1105, -0.0206,  0.0440]], grad_fn=<MmBackward0>)

In [35]:
y1-y2

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], grad_fn=<SubBackward0>)